chore: Adding CoC, ReadMe and Makefile
notaryproject/notation-plugin-framework-go pull request #11
Opened 2024-01-17 15:00 UTC by priteshbandi

chore: Adding CoC, ReadMe and Makefile

2024-01-17 20:21 UTC, rgnote approved these changes

2024-01-18 02:02 UTC, Two-Hearts commented on CODE_OF_CONDUCT.md
I think we don't have to add this file manually? There's one here: https://github.com/notaryproject/.github/blob/main/CODE_OF_CONDUCT.md, the repo will automatically link to this file.

2024-01-18 02:31 UTC, shizhMSFT requested changes

2024-01-18 02:31 UTC, shizhMSFT commented on README.md
Since this repository is not stabilized, please add the following warning in the `README.md` file.
> [!WARNING]
> This project is currently under initial development. APIs may and will be changed incompatibly from one commit to another.

2024-01-18 11:55 UTC, priteshbandi commented on README.md
Isnt this already conveyed by not having a release?

2024-01-18 13:11 UTC, priteshbandi commented on README.md
I am planning for 1.0 release directly as its only refactoring of code to allow plugin as library.

2024-01-18 13:19 UTC, merged