Adding validation for request input.
notaryproject/notation-plugin-framework-go pull request #12
Opened 2024-01-19 16:11 UTC by priteshbandi

Adding validation for request input.

2024-01-22 01:53 UTC, Two-Hearts commented on cli/cli.go
> +		c.logger.Errorf("%s validation error :%v", reflect.TypeOf(request), err)
nit:
```suggestion
		c.logger.Errorf("%s validation error: %v", reflect.TypeOf(request), err)
```

2024-01-22 01:53 UTC, Two-Hearts commented on cli/cli.go
> +		if e, ok := err.(*plugin.Error); ok {
Do we need to check this? Because errors from `request.Validate()` is always `nil` or `*plugin.Error`.

2024-01-22 01:53 UTC, Two-Hearts commented on plugin/errors.go
> +func NewValidationErrorf(format string, msg ...any) *Error {
Since `Error` struct is also used to represent a request validation error, its description needs to be updated: line 37 & 38.

2024-01-22 06:36 UTC, Two-Hearts commented on cli/cli.go
> +		if e, ok := err.(*plugin.Error); ok {
@priteshbandi I couldn't see the changes though, you might forget to push them?

2024-01-22 08:53 UTC, JeyJeyGao approved these changes
LGTM, Pending on @patrickzheng200 's comments.

2024-01-22 09:26 UTC, JeyJeyGao requested changes
Pending on @Two-Hearts 's comments.

2024-01-22 23:48 UTC, Two-Hearts approved these changes
LGTM

2024-01-23 02:02 UTC, JeyJeyGao approved these changes
LGTM

2024-01-23 02:02 UTC, merged